### ISSUE TITLE
There is no method to delete entry from table without 'id' column

### ISSUE THREAD

**Issue by aczekajski** [tomaszkiewicz/algorest#1]
Using algorest for table that joins two entities in many to many relation, leaves no method to delete entry from this joining table.

Lets consider an example with "users_claims" table which joins "users" with "claims". I want to delete an entry from "users_claims" with userId equal to 1 and claimId equal to 4. I've tried the following request:
`DELETE /users_claims?$filter=(userId eq '1') and (claimId eq '4')`
but it obviously returns 404 error because of no id in path. The best situation would be if one could specify which columns create composite key like that:

``` javascript
var options = {
    compositeKey: ['userId', 'claimId']
}
app.rest('users_claims',options);
```

and delete entries like that:
`DELETE /users_claims/1/4`

**Comment by tomaszkiewicz** [comment]
There was an assumption at the time I created algorest that all tables, including tables that represents n-to-n relations have id column, so use that column instead.
