### ISSUE TITLE
Filtering with multiple "or" doesn't work properly

### ISSUE THREAD

**Issue by aczekajski** [tomaszkiewicz/algorest#2]
When performing request such as:
`/some_collection?$filter=(id eq '1') or (id eq '2') or (id eq '3')`
The query to database asks only about id 1 and 2.

There also should be a possibility to do
`?$filter=id in (1,2,3)`

**Comment by tomaszkiewicz** [comment]
The parser for oData has changed in last version. It now includes support for IN statement. Check newSqlParser branch for latest versions (the branch will be merged into v2 after testing).
