### ISSUE TITLE
There are no callbacks to get action

### ISSUE THREAD

**Issue by aczekajski** [tomaszkiewicz/algorest#5]
There is no way to manipulate data before sending. There should be method "beforeSend" that allows to do so. Use case for that is for example to get rid os "password" or "salt" fields when GET to users table is performed.

**Comment by tomaszkiewicz** [comment]
There is "blacklist" option implemented for cases like that.
Sample usage:

``` js
    app.rest('users', {
      authenticate: authenticate,
      where: function(req) { return { id: req.user.id }},
      blacklist: [ 'hash', 'salt' ]
    });
```
